CREATE DATABASE IF NOT EXISTS TaskDB;
USE TaskDB;

CREATE TABLE IF NOT EXISTS Task(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  description TEXT,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
